import os

base_path = r'C:\Users\dammy.OLUWADAMILOLA\VS Developer\WebScraper\Tesco'

categories = [
    'Frozen Food',
    'Drinks',
    'Baby',
    'Health & Beauty',
    'Pets',
    'Household',
    'Home & Living',
    'Tesco Finest',
    'Fresh Food',
    'Bakery',
    'Food Cupboard'
]

subcategories = {
    'Fresh Food': [
        'All Fresh Food',
        'Fresh Fruit',
        'Fresh Vegetables',
        'Salads & Dips',
        'Milk, Butter & Eggs',
        'Cheese',
        'Yoghurt',
        'Dairy Alternatives',
        'Fresh Meat & Poultry',
        'Stuffing & Accompaniments',
        'Chilled Fish & Sea Food',
        'Cooked Meat',
        'Continental Meats & Antipasti',
        'Chilled Food',
        'Chilled Desserts',
        'Fresh Meals, Pizza, Pasta & Garlic Bread',
        'Savoury Pastry',
        'Charity of the Year Contribution',
        'Flowers',
        'Juices & Smoothies',
        'Meat Free',
        'Offers on Fresh Food'
    ],
    'Bakery': [
        'All Bakery',
        'In Store Bakery',
        'Bread',
        'Croissants & Pastries',
        'Crumpets & Pancakes',
        'Cakes & Pies',
        'Doughnuts, Muffins & Cookies',
        'Flans & Pastry',
        'Specialist Bakery',
        'Christmas Bakery',
        'Charity of the Year Contribution',
        'Cakes, Cake Bars, Slices & Pies',
        'Finest Bakery',
        'From Our Bakery',
        'Fruit Loaves, Hot Cross Buns & Scones',
        'Pancakes, Waffles, Farls & Crumpets',
        'Offers on Bakery'
    ],
    'Food Cupboard': [
        "Food Cupboard",
        "Tins & Packets",
        "Cooking Ingredients",
        "Dried Pasta, Rice, Noodles & Cous Cous",
        "Cooking Sauces & Meal Kits",
        "Condiments & Table Sauces",
        "Pickles, Chutneys & Olives",
        "Baking, Desserts & Spreads",
        "Biscuits",
        "Chocolate",
        "Sweets, Mints & Chewing Gum",
        "Sugar & Sweeteners",
        "Organic & Free From",
        "Foods of the World",
        "Christmas Treats",
        "Charity of the Year Contribution",
        "Crisps, Nuts and Popcorn",
        "Breakfast Cereals",
        "Tea",
        "Coffee",
        "Hot Chocolate & Malted Drinks",
        "Hot Drinks",
        "Offers on Food Cupboard"
    ],
    'Frozen Food': [
        "Frozen Food",
        "Frozen Meat & Poultry",
        "Frozen Fish & Seafood",
        "Frozen Free From",
        "Frozen Ice Cream & Desserts",
        "Frozen Fruit & Ice Cubes",
        "Frozen Ready Meals, Pizza & Yorkshires",
        "Frozen Chips, Potatoes & Onion Rings",
        "Frozen Vegetables",
        "Charity of the Year Contribution",
        "Offers on Frozen Food"
    ],
    'Drinks': [
        "All Drinks",
        "Water",
        "Adult Soft Drinks, Cordials and Teas",
        "Fizzy Drinks",
        "Juice",
        "Kids Fruit Drinks and Water",
        "Mixers, Tonic and Soda Water",
        "On The Go Drinks",
        "Sports and Energy Drinks",
        "Squash and Cordials",
        "Beer & Cider",
        "Wine",
        "Spirits",
        "Tea",
        "Coffee",
        "Hot Chocolate & Malted Drinks",
        "Speciality",
        "Alcohol Free & Low Alcohol Drinks",
        "Offers on Drinks"
    ],
    'Baby': [
        "All Baby",
        "Nappies",
        "Baby & Toddler Wipes",
        "Baby Toiletries",
        "Baby Healthcare",
        "Baby & Toddler Milk",
        "Baby & Toddler Food",
        "Accessories",
        "Eco-Friendly Baby",
        "Offers on Baby"
    ],
    'Health & Beauty': [
        "All Health & Beauty",
        "Haircare",
        "Oral Care",
        "Feminine Care",
        "Beauty & Skincare",
        "Health Care",
        "Mens Toiletries",
        "Toiletries",
        "Deodorants & Body Sprays",
        "Cosmetics",
        "Eye Care",
        "Incontinence and Bladder Weakness",
        "Eco-Friendly Health & Beauty",
        "Medicine",
        "Offers on Health & Beauty"
    ],
    'Pets': [
        "All Pets",
        "Cat & Kitten",
        "Dog & Puppy",
        "Small Animal, Fish and Bird",
        "Offers on Pets"
    ],
    'Household': [
        "All Household",
        "Cleaning",
        "Dishwashers & Washing Up",
        "Eco Friendly",
        "Food Storage",
        "Home Fragrance",
        "Household Sundries",
        "Laundry",
        "Toilet Paper, Kitchen Rolls & Tissues",
        "Cleaning Tools & Gloves",
        "Offers on Household"
    ],
    'Home & Living': [
        "All Home & Living",
        "Paperchase",
        "Electrical",
        "Home Essentials",
        "Party Decorations & Party Supplies",
        "Toys & Games",
        "Stationery, Arts & Crafts",
        "Newspapers, Magazines & Tobacconist",
        "Charity Donation",
        "Flowers",
        "Tesco Mobile",
        "Eco-Friendly Home & Ents",
        "Greeting Cards",
        "Garden & Outdoor",
        "Back to School",
        "Party & Giftwrap",
        "Offers on Home & Living"
    ],
    'Tesco Finest': [
        "All Tesco Finest",
        "Finest Fresh Food",
        "Finest Bakery",
        "Finest Drinks",
        "Finest Food Cupboard",
        "Finest Frozen Food",
        "Offers on Tesco Finest"
    ],
}

subcategories = {
    'Fresh Food': {
        'All Fresh Food': '/groceries/en-IE/shop/fresh-food/all?include-children=true',
        'Fresh Fruit': {
            'All Fresh Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/all?include-children=true',
            'Apples, Pears & Rhubarb': '/groceries/en-IE/shop/fresh-food/fresh-fruit/apples-pears-and-rhubarb?include-children=true',
            'Avocados': '/groceries/en-IE/shop/fresh-food/fresh-fruit/avocados?include-children=true',
            'Bananas': '/groceries/en-IE/shop/fresh-food/fresh-fruit/bananas?include-children=true',
            'Berries & Cherries': '/groceries/en-IE/shop/fresh-food/fresh-fruit/berries-and-cherries?include-children=true',
            'Citrus Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/citrus-fruit?include-children=true',
            'Dried Fruit & Nuts': '/groceries/en-IE/shop/fresh-food/fresh-fruit/dried-fruit-and-nuts?include-children=true',
            'Grapes': '/groceries/en-IE/shop/fresh-food/fresh-fruit/grapes?include-children=true',
            'Nectarines & Peaches': '/groceries/en-IE/shop/fresh-food/fresh-fruit/nectarines-and-peaches?include-children=true',
            'Organic Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/organic-fruit?include-children=true',
            'Plums & Apricots': '/groceries/en-IE/shop/fresh-food/fresh-fruit/plums-and-apricots?include-children=true',
            'Prepared Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/prepared-fruit?include-children=true',
            'Tropical & Exotic Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/tropical-and-exotic-fruit?include-children=true',
            'Offers on Fresh Fruit': '/groceries/en-IE/shop/fresh-food/fresh-fruit/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Fresh Vegetables': {
            'All Fresh Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/all?include-children=true',
            'Baby Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/baby-vegetables?include-children=true',
            'Broccoli, Cauliflower & Cabbage': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/broccoli-cauliflower-and-cabbage?include-children=true',
            'Carrots & Root Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/carrots-and-root-vegetables?include-children=true',
            'Chillies, Garlic & Ginger': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/chillies-garlic-and-ginger?include-children=true',
            'Courgettes, Aubergines & Asparagus': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/courgettes-aubergines-and-asparagus?include-children=true',
            'Mushrooms': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/mushrooms?include-children=true',
            'Onions & Shallots': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/onions-and-shallots?include-children=true',
            'Organic Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/organic-vegetables?include-children=true',
            'Peas, Beans & Sweetcorn': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/peas-beans-and-sweetcorn?include-children=true',
            'Potatoes': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/potatoes?include-children=true',
            'Prepared Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/prepared-vegetables?include-children=true',
            'Seasonal Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/seasonal-vegetables?include-children=true',
            'Spinach, Greens & Kale': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/spinach-greens-and-kale?include-children=true',
            'Stir Fry': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/stir-fry?include-children=true',
            'Offers on Fresh Vegetables': '/groceries/en-IE/shop/fresh-food/fresh-vegetables/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Salads & Dips': {
            'All Salads & Dips': '/groceries/en-IE/shop/fresh-food/salads-and-dips/all?include-children=true',
            'Chilled Dips': '/groceries/en-IE/shop/fresh-food/salads-and-dips/chilled-dips?include-children=true',
            'Coleslaw & Dressed Salads': '/groceries/en-IE/shop/fresh-food/salads-and-dips/coleslaw-and-dressed-salads?include-children=true',
            'Fresh Herbs, Chillies & Spices': '/groceries/en-IE/shop/fresh-food/salads-and-dips/fresh-herbs-chillies-and-spices?include-children=true',
            'Prepared Salad & Salad Bags': '/groceries/en-IE/shop/fresh-food/salads-and-dips/prepared-salad-and-salad-bags?include-children=true',
            'Salad Vegetables': '/groceries/en-IE/shop/fresh-food/salads-and-dips/salad-vegetables?include-children=true',
            'Tomatoes': '/groceries/en-IE/shop/fresh-food/salads-and-dips/tomatoes?include-children=true',
            'Offers on Salads & Dips': '/groceries/en-IE/shop/fresh-food/salads-and-dips/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Milk, Butter & Eggs': {
            'All Milk, Butter & Eggs': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/all?include-children=true',
            'Butter, Spreads & Margarine': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/butter-spreads-and-margarine?include-children=true',
            'Eggs': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/eggs?include-children=true',
            'Fresh Cream & Custard': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/fresh-cream-and-custard?include-children=true',
            'Fresh Milk': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/fresh-milk?include-children=true',
            'Baking & Cooking': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/baking-and-cooking?include-children=true',
            'Offers on Milk, Butter & Eggs': '/groceries/en-IE/shop/fresh-food/milk-butter-and-eggs/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Cheese': {
            'All Cheese': '/groceries/en-IE/shop/fresh-food/cheese/all?include-children=true',
            'Cheese Boards & Gifts': '/groceries/en-IE/shop/fresh-food/cheese/cheese-boards-and-gifts?include-children=true',
            'Cheddar Cheese': '/groceries/en-IE/shop/fresh-food/cheese/cheddar-cheese?include-children=true',
            'Cheese Spreads & Snacks': '/groceries/en-IE/shop/fresh-food/cheese/cheese-spreads-and-snacks?include-children=true',
            'Cottage & Soft Cheese': '/groceries/en-IE/shop/fresh-food/cheese/cottage-and-soft-cheese?include-children=true',
            'Sliced & Grated Cheese': '/groceries/en-IE/shop/fresh-food/cheese/sliced-and-grated-cheese?include-children=true',
            'Speciality & Continental Cheese': '/groceries/en-IE/shop/fresh-food/cheese/speciality-and-continental-cheese?include-children=true',
            'Offers on Cheese': '/groceries/en-IE/shop/fresh-food/cheese/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Yoghurt': {
            'All Yoghurt': '/groceries/en-IE/shop/fresh-food/yoghurt/all?include-children=true',
            'Yoghurts': '/groceries/en-IE/shop/fresh-food/yoghurt/yoghurts?include-children=true',
            'Yoghurt Drinks': '/groceries/en-IE/shop/fresh-food/yoghurt/yoghurt-drinks?include-children=true',
            'Offers on Yoghurt': '/groceries/en-IE/shop/fresh-food/yoghurt/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Dairy Alternatives': {
            'All Dairy Alternatives': '/groceries/en-IE/shop/fresh-food/dairy-alternatives/all?include-children=true',
            'Dairy Alternatives': '/groceries/en-IE/shop/fresh-food/dairy-alternatives/dairy-alternatives?include-children=true',
            'Offers on Dairy Alternatives': '/groceries/en-IE/shop/fresh-food/dairy-alternatives/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Fresh Meat & Poultry': {
            'All Fresh Meat & Poultry': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/all?include-children=true',
            'Fresh Bacon': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-bacon?include-children=true',
            'Fresh Beef': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-beef?include-children=true',
            'Fresh Chicken': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-chicken?include-children=true',
            'Fresh Duck': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-duck?include-children=true',
            'Fresh Lamb': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-lamb?include-children=true',
            'Fresh Pork': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-pork?include-children=true',
            'Fresh Turkey': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/fresh-turkey?include-children=true',
            'Ready to Cook': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/ready-to-cook?include-children=true',
            'Breaded Poultry': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/breaded-poultry?include-children=true',
            'Sausages': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/sausages?include-children=true',
            'BBQ': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/bbq?include-children=true',
            'Pudding': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/pudding?include-children=true',
            'Rashers': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/rashers?include-children=true',
            'Offers on Fresh Meat & Poultry': '/groceries/en-IE/shop/fresh-food/fresh-meat-and-poultry/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Stuffing & Accompaniments': {
            'All Stuffing & Accompaniments': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/all?include-children=true',
            'Breadcrumbs & Stuffing': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/breadcrumbs-and-stuffing?include-children=true',
            'Sauces': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/sauces?include-children=true',
            'Breadcrumbs': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/breadcrumbs?include-children=true',
            'Stuffing': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/stuffing?include-children=true',
            'Other': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/other?include-children=true',
            'Offers on Stuffing & Accompaniments': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Stuffing & Accompaniments': {
            'All Stuffing & Accompaniments': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/all?include-children=true',
            'Breadcrumbs & Stuffing': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/breadcrumbs-and-stuffing?include-children=true',
            'Sauces': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/sauces?include-children=true',
            'Breadcrumbs': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/breadcrumbs?include-children=true',
            'Stuffing': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/stuffing?include-children=true',
            'Other': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/other?include-children=true',
            'Offers on Stuffing & Accompaniments': '/groceries/en-IE/shop/fresh-food/stuffing-and-accompaniments/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Chilled Fish & Sea Food': {
            'All Chilled Fish & Sea Food': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/all?include-children=true',
            'Breaded & Prepared': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/breaded-and-prepared?include-children=true',
            'Cod, Haddock & White Fish': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/cod-haddock-and-white-fish?include-children=true',
            'Mackerel': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/mackerel?include-children=true',
            'Prawns & Seafood': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/prawns-and-seafood?include-children=true',
            'Ready to Cook': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/ready-to-cook?include-children=true',
            'Salmon & Trout': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/salmon-and-trout?include-children=true',
            'Smoked Fish': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/smoked-fish?include-children=true',
            'Offers on Chilled Fish & Sea Food': '/groceries/en-IE/shop/fresh-food/chilled-fish-and-sea-food/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Cooked Meat': {
            'All Cooked Meat': '/groceries/en-IE/shop/fresh-food/cooked-meat/all?include-children=true',
            'Cooked Chicken & Turkey': '/groceries/en-IE/shop/fresh-food/cooked-meat/cooked-chicken-and-turkey?include-children=true',
            'Deli Counter Cooked Meats': '/groceries/en-IE/shop/fresh-food/cooked-meat/deli-counter-cooked-meats?include-children=true',
            'Frankfurters & Snacking': '/groceries/en-IE/shop/fresh-food/cooked-meat/frankfurters-and-snacking?include-children=true',
            'Sliced Beef': '/groceries/en-IE/shop/fresh-food/cooked-meat/sliced-beef?include-children=true',
            'Sliced Ham': '/groceries/en-IE/shop/fresh-food/cooked-meat/sliced-ham?include-children=true',
            'Value Ham & Luncheon Meats': '/groceries/en-IE/shop/fresh-food/cooked-meat/value-ham-and-luncheon-meats?include-children=true',
            'Polish Cooked Meat': '/groceries/en-IE/shop/fresh-food/cooked-meat/polish-cooked-meat?include-children=true',
            'Offers on Cooked Meat': '/groceries/en-IE/shop/fresh-food/cooked-meat/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Continental Meats & Antipasti': {
            'All Continental Meats & Antipasti': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/all?include-children=true',
            'Chorizo & Pancetta': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/chorizo-and-pancetta?include-children=true',
            'Continental Cooked Ham': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/continental-cooked-ham?include-children=true',
            'Continental Meat Platters': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/continental-meat-platters?include-children=true',
            'Olives & Antipasti': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/olives-and-antipasti?include-children=true',
            'Parma Ham, Prosciutto & Serrano Ham': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/parma-ham-prosciutto-and-serrano-ham?include-children=true',
            'Pate': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/pate?include-children=true',
            'Salami & Pepperoni': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/salami-and-pepperoni?include-children=true',
            'Offers on Continental Meats & Antipasti': '/groceries/en-IE/shop/fresh-food/continental-meats-and-antipasti/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Chilled Food': {
            'All Chilled Food': '/groceries/en-IE/shop/fresh-food/chilled-food/all?include-children=true',
            'Polish Food': '/groceries/en-IE/shop/fresh-food/chilled-food/polish-food?include-children=true',
            'Offers on Chilled Food': '/groceries/en-IE/shop/fresh-food/chilled-food/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },

        'Chilled Desserts': {
            'All Chilled Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/all?include-children=true',
            'Chilled Dessert': '/groceries/en-IE/shop/fresh-food/chilled-desserts/chilled-dessert?include-children=true',
            'Sponges, Pies & Puddings': '/groceries/en-IE/shop/fresh-food/chilled-desserts/sponges-pies-and-puddings?include-children=true',
            'Trifles & Cheesecakes': '/groceries/en-IE/shop/fresh-food/chilled-desserts/trifles-and-cheesecakes?include-children=true',
            'Fresh Cream Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/fresh-cream-desserts?include-children=true',
            'Individual Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/individual-desserts?include-children=true',
            'Indulgent Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/indulgent-desserts?include-children=true',
            'Rice Puddings': '/groceries/en-IE/shop/fresh-food/chilled-desserts/rice-puddings?include-children=true',
            'Low Fat Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/low-fat-desserts?include-children=true',
            'Offers on Chilled Desserts': '/groceries/en-IE/shop/fresh-food/chilled-desserts/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Fresh Meals, Pizza, Pasta & Garlic Bread': {
            'All Fresh Meals, Pizza, Pasta & Garlic Bread': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/all?include-children=true',
            'Fresh Garlic & Cheese Breads': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/fresh-garlic-and-cheese-breads?include-children=true',
            'Fresh Pasta': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/fresh-pasta?include-children=true',
            'Fresh Pasta Sauce & Pesto': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/fresh-pasta-sauce-and-pesto?include-children=true',
            'Fresh Pizza': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/fresh-pizza?include-children=true',
            'Party Food': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/party-food?include-children=true',
            'Prepared Meals': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/prepared-meals?include-children=true',
            'Sandwiches, Snacks & Sushi': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/sandwiches-snacks-and-sushi?include-children=true',
            'Stock, Soup & Sauces': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/stock-soup-and-sauces?include-children=true',
            'Chilled Ready Meals': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/chilled-ready-meals?include-children=true',
            'Offers on Fresh Meals, Pizza, Pasta & Garlic Bread': '/groceries/en-IE/shop/fresh-food/fresh-meals-pizza-pasta-and-garlic-bread/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Savoury Pastry': {
            'All Savoury Pastry': '/groceries/en-IE/shop/fresh-food/savoury-pastry/all?include-children=true',
            'Pies, Quiche & Pasties': '/groceries/en-IE/shop/fresh-food/savoury-pastry/pies-quiche-and-pasties?include-children=true',
            'Sausage Rolls, Cocktail Sausages & Scotch Eggs': '/groceries/en-IE/shop/fresh-food/savoury-pastry/sausage-rolls-cocktail-sausages-and-scotch-eggs?include-children=true',
            'Offers on Savoury Pastry': '/groceries/en-IE/shop/fresh-food/savoury-pastry/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Flowers': {
            'All Flowers': '/groceries/en-IE/shop/fresh-food/flowers/all?include-children=true',
            'Bouquet': '/groceries/en-IE/shop/fresh-food/flowers/bouquet?include-children=true',
            'Offers on Flowers': '/groceries/en-IE/shop/fresh-food/flowers/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Juices & Smoothies': {
            'All Juices & Smoothies': '/groceries/en-IE/shop/fresh-food/juices-and-smoothies/all?include-children=true',
            'Chilled Juice': '/groceries/en-IE/shop/fresh-food/juices-and-smoothies/chilled-juice?include-children=true',
            'Coconut Water': '/groceries/en-IE/shop/fresh-food/juices-and-smoothies/coconut-water?include-children=true',
            'Smoothies': '/groceries/en-IE/shop/fresh-food/juices-and-smoothies/smoothies?include-children=true',
            'Offers on Juices & Smoothies': '/groceries/en-IE/shop/fresh-food/juices-and-smoothies/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },
        'Meat Free': {
            'All Meat Free': '/groceries/en-IE/shop/fresh-food/meat-free/all?include-children=true',
            'Meat Free Bacon & Pudding': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-bacon-and-pudding?include-children=true',
            'Meat Free Burgers': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-burgers?include-children=true',
            'Meat Free Chicken': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-chicken?include-children=true',
            'Meat Free Deli Slices': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-deli-slices?include-children=true',
            'Meat Free Mince & Meatballs': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-mince-and-meatballs?include-children=true',
            'Meat Free Other': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-other?include-children=true',
            'Meat Free Sausages': '/groceries/en-IE/shop/fresh-food/meat-free/meat-free-sausages?include-children=true',
            'Ready Meals': '/groceries/en-IE/shop/fresh-food/meat-free/ready-meals?include-children=true',
            'Tofu & Tempeh': '/groceries/en-IE/shop/fresh-food/meat-free/tofu-and-tempeh?include-children=true',
            'Offers on Meat Free': '/groceries/en-IE/shop/fresh-food/meat-free/all?viewAll=promotion&amp;promotion=offers?include-children=true',
        },






        
        # ... (other subcategories for Fresh Food)
    },
    # ... (other categories with their respective subcategories)
}


for category in categories:
    category_path = os.path.join(base_path, category)
    os.makedirs(category_path, exist_ok=True)
    print(f'Created folder: {category_path}')

    if category in subcategories:
        for subcategory in subcategories[category]:
            subcategory_path = os.path.join(category_path, subcategory)
            os.makedirs(subcategory_path, exist_ok=True)
            print(f'Created folder: {subcategory_path}')
